/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParametersWrap */

#ifndef _Included_ParametersWrap
#define _Included_ParametersWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ParametersWrap
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_initialize
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    setDevicePort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_setDevicePort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ParametersWrap
 * Method:    getDevicePort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ParametersWrap_getDevicePort
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    setSigslotsNamespace
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_setSigslotsNamespace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ParametersWrap
 * Method:    getSigslotsNamespace
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ParametersWrap_getSigslotsNamespace
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    setEnableAccelerationLimiter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_setEnableAccelerationLimiter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ParametersWrap
 * Method:    getEnableAccelerationLimiter
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ParametersWrap_getEnableAccelerationLimiter
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    setBatteryCapacity
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_setBatteryCapacity
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ParametersWrap
 * Method:    getBatteryCapacity
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ParametersWrap_getBatteryCapacity
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    setBatteryLow
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_setBatteryLow
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ParametersWrap
 * Method:    getBatteryLow
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ParametersWrap_getBatteryLow
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    setBatteryDangerous
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_setBatteryDangerous
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ParametersWrap
 * Method:    getBatteryDangerous
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ParametersWrap_getBatteryDangerous
  (JNIEnv *, jobject);

/*
 * Class:     ParametersWrap
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ParametersWrap_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
