/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KobukiWrap */

#ifndef _Included_KobukiWrap
#define _Included_KobukiWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KobukiWrap
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_KobukiWrap_initialize
  (JNIEnv *, jobject);

/*
 * Class:     KobukiWrap
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_KobukiWrap_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     KobukiWrap
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_KobukiWrap_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
